---
  - name: Creating node_exporter user group
    group: 
      name: node_exporter

  - name: Creatinf node-exporter user
    user:
      name: node_exporter
      group: node_exporter
      system: yes
      shell: "/sbin/nologin"
      comment: "node_exporter nologin User"
      create_home: "no"
      state: present 

  - name: Download node exprorter binary to local folder
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
      dest: "/tmp/"
      remote_src: yes

  - name: Move node-exporter
    copy:
      src: "/tmp/node_exporter-1.1.2.linux-amd64/node_exporter"
      dest:  "/usr/local/bin/node_exporter"
      owner: node_exporter
      group: node_exporter
      mode: 0755
      remote_src: yes

  - name: delete node exporter tmp folder 
    file:
      path: /tmp/node_exporter-1.1.2.linux-amd64"
      state: absent

  - name: Copy the node_exporter systemd unit
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service

  - name:  node_exporter is running
    service: 
      name: node_exporter 
      state: started
      enabled: true

  - name: Chef if node exporter emits metrics
    uri: 
      url: http://127.0.0.1:9100/metrics
      method: GET 
      status_code: 200
